# Generated by Django 3.2.6 on 2021-08-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('email', models.EmailField(max_length=250, null=True)),
                ('username', models.CharField(max_length=250, null=True)),
                ('password', models.CharField(max_length=300, null=True)),
                ('mobile', models.CharField(max_length=250, null=True)),
                ('email_otp', models.IntegerField(null=True)),
                ('email_verify_status', models.BooleanField(default=False)),
                ('reset_token', models.CharField(max_length=250, null=True)),
                ('auth_token', models.CharField(max_length=250, null=True)),
                ('customer_status', models.CharField(default='active', max_length=250, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
