# Generated by Django 3.2.6 on 2021-08-11 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='email_verify_status',
            new_name='email_verified',
        ),
    ]
