# Generated by Django 3.2.6 on 2021-08-12 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_email_verify_status_customers_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=250, null=True)),
                ('patterns', models.TextField(null=True)),
                ('responses', models.TextField(null=True)),
                ('render_status', models.CharField(default='raw', max_length=250, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('customers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customers')),
            ],
        ),
    ]
